### PR TITLE
Replace BurntSushi/toml with pelletier/go-toml

### PR DESCRIPTION
**Pull request by thaJeztah**
BurntSushi/toml is no longer maintained, and the ecosystem looks to be converging to using pelletier/go-toml

### CODE REVIEW

**Comment by thaJeztah** [comment]
This will probably conflict with https://github.com/stevvooe/protobuild/pull/32 - I'll rebase after that's merged

**Comment by stevvooe** [comment]
@thaJeztah Sorry for not merging #32 earlier. It's now merged. Could you rebase?

**Comment by thaJeztah** [comment]
Rebased 👍

**Comment by thaJeztah** [comment]
Probably need to move this to use github actions as well, as it's still using travis.org (which will be shut down end of this month) 🤔

**Pull request merged**
