### PR TITLE
Handle the file path manipulation slightly better

### PR DESCRIPTION
**Pull request by bruceadowns**
* use filepath.Join rather than concatenate file paths
* based on review feedback

Signed-off-by: Bruce Downs <bruce.downs@jivesoftware.com>

### CODE REVIEW

**Comment by bruceadowns** [comment]
Hey @stevvooe, I figured I'd submit your suggestion while I'm in here. I'll checkout the file include issue we talked about, too.

**Comment by stevvooe** [comment]
LGTM

**Comment by bruceadowns** [comment]
I just noticed I had added the protobuild binary. D'oh!

**Comment by stevvooe** [comment]
@bruceadowns No worries, took us a bit too notice, as well.

**Pull request merged**
